apiVersion: k8s.cloudogu.com/v3
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
  name: blueprint
spec:
  displayName: blueprint
  blueprint:
    dogus:
      - name: official/cas
        version: "7.2.7-12"
      - name: official/postfix
        version: "3.10.8-2"
      - name: official/ldap
        version: "2.6.10-5"
      - name: official/redmine
        version: "6.1.1-6"
      - name: official/postgresql
        version: "14.21-2"
<#if config.content.variables.fqdn??>
    config:
      global:
        - key: fqdn
          value: "${config.content.variables.fqdn}"
</#if>
